# -*- coding: utf-8 -*-
"""Program 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FKgKELULyzDrePdueOqshRaaKVZQq15C

#PROGRAM 5

##Keadaan 1
"""

import math

#Titik pusat cluster
A=(2,1,3)
B=(1,-4,6)
C=(-2,3,-2)

#input titik U
x1=1
x2=-4
x3=6
U=(x1,x2,x3)

#Rumus jarak:
def jarak(p, q):
  hasil_jarak=math.sqrt((p[0]-q[0])**2 + (p[1]-q[1])**2 + (p[2]-q[2])**2)
  return hasil_jarak

#Menghitung jarak ke pusat cluster
dA = jarak(U,A)
dB = jarak(U,B)
dC = jarak(U,C)

#Menentukan cluster terdekat
if dA<dB and dA<dC:
  cluster="cluster A"
elif dB<dA and dB<dC:
  cluster="cluster B"
elif dC<dA and dC< dB:
  cluster = "cluster C"
elif dA==dB and dA<dC:
  cluster="Perbatasan cluster A dan B"
elif dA==dC and dA<dB:
  cluster="Perbatasan cluster A dan C"
elif dB==dC and dB<dA:
  cluster="Perbatasan cluster B dan C"
else:
  cluster="Perbatasan cluster A, B, dan C"

#Tampikan hasil
print(f"Koordinat titik U : {U}")
print(f"Jarak U ke A : {dA:.4f}")
print(f"Jarak U ke B : {dB:.4f}")
print(f"Jarak U ke C : {dC:.4f}")
print(f"Titik tergolong {cluster}")

"""##Keadaan 2"""

import math

#Titik pusat cluster
A=(2,1,3)
B=(1,-4,6)
C=(-2,3,-2)

#input titik U
x1=4
x2=2
x3=3
U=(x1,x2,x3)

#Rumus jarak:
def jarak(p, q):
  hasil_jarak=math.sqrt((p[0]-q[0])**2 + (p[1]-q[1])**2 + (p[2]-q[2])**2)
  return hasil_jarak

#Menghitung jarak ke pusat cluster
dA = jarak(U,A)
dB = jarak(U,B)
dC = jarak(U,C)

#Menentukan cluster terdekat
if dA<dB and dA<dC:
  cluster="cluster A"
elif dB<dA and dB<dC:
  cluster="cluster B"
elif dC<dA and dC< dB:
  cluster = "cluster C"
elif dA==dB and dA<dC:
  cluster="Perbatasan cluster A dan B"
elif dA==dC and dA<dB:
  cluster="Perbatasan cluster A dan C"
elif dB==dC and dB<dA:
  cluster="Perbatasan cluster B dan C"
else:
  cluster="Perbatasan cluster A, B, dan C"

#Tampikan hasil
print(f"Koordinat titik U : {U}")
print(f"Jarak U ke A : {dA:.4f}")
print(f"Jarak U ke B : {dB:.4f}")
print(f"Jarak U ke C : {dC:.4f}")
print(f"Titik tergolong {cluster}")

"""##Keadaan 3

"""

import math

#Titik pusat cluster
A=(2,1,3)
B=(1,-4,6)
C=(-2,3,-2)

#input titik U
x1=1.5
x2=-1.5
x3=4.5
U=(x1,x2,x3)

#Rumus jarak:
def jarak(p, q):
  hasil_jarak=math.sqrt((p[0]-q[0])**2 + (p[1]-q[1])**2 + (p[2]-q[2])**2)
  return hasil_jarak

#Menghitung jarak ke pusat cluster
dA = jarak(U,A)
dB = jarak(U,B)
dC = jarak(U,C)

#Menentukan cluster terdekat
if dA<dB and dA<dC:
  cluster="cluster A"
elif dB<dA and dB<dC:
  cluster="cluster B"
elif dC<dA and dC< dB:
  cluster = "cluster C"
elif dA==dB and dA<dC:
  cluster="Perbatasan cluster A dan B"
elif dA==dC and dA<dB:
  cluster="Perbatasan cluster A dan C"
elif dB==dC and dB<dA:
  cluster="Perbatasan cluster B dan C"
else:
  cluster="Perbatasan cluster A, B, dan C"

#Tampikan hasil
print(f"Koordinat titik U : {U}")
print(f"Jarak U ke A : {dA:.4f}")
print(f"Jarak U ke B : {dB:.4f}")
print(f"Jarak U ke C : {dC:.4f}")
print(f"Titik tergolong {cluster}")
